#!/bin/bash

echo Pulling repository...
git pull
echo Changing Directory...
cd "Plus0 Bot"
echo Copying config.json to binary directory...
cp settings.json bin/Debug/netcoreapp2.0/Data/settings.json
echo Restoring Nuget Packages...
dotnet restore
echo Running +0...
dotnet run