#!/bin/bash

echo Pulling repository...
git pull
echo Changing Directory...
cd "SquidDraftLeague.Bot"
echo Copying config.json to binary directory...
cp Data/settings.json bin/Debug/netcoreapp2.1/Data/settings.json
echo Restoring Nuget Packages...
dotnet restore
echo Running SquidDraftLeague.Bot...
dotnet run --project ./SquidDraftLeague.Bot.csproj